workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - cd example && flutter packages pub get
      - cd example && flutter build apk --debug
      - cd example && flutter build ios --debug

    artifacts:
      - example/flutter_drive.log
    publishing:
      email:
        recipients:
          - rafaelsantosferraz@gmail.com
